#Settings
PLAYER_HEALTH = 20
CPU_HEALTH = 20

PLAYER_STARTING_MANA = 1
CPU_STARTING_MANA = 1 

PLAYER_STARTING_HAND = 3
CPU_STARTING_HAND = 4

#CPU

PAWN_SUMMON_WEIGHT = 1
BISHOP_SUMMON_WEIGHT = 2
ROOK_SUMMON_WEIGHT = 2
QUEEN_SUMMON_WEIGHT = 5

PAWN_DAMAGE_WEIGHT = 1
BISHOP_DAMAGE_WEIGHT = 2
ROOK_DAMAGE_WEIGHT = 2
QUEEN_DAMAGE_WEIGHT = 4

PAWN_HEAL_WEIGHT = 1
BISHOP_HEAL_WEIGHT = 2
ROOK_HEAL_WEIGHT = 2
QUEEN_HEAL_WEIGHT = 4

PAWN_KILL_WEIGHT = 2
BISHOP_KILL_WEIGHT = 4
ROOK_KILL_WEIGHT = 4
QUEEN_KILL_WEIGHT = 8

PLAYER_DAMAGE_WEIGHT = 1

